name: Generate and Push SVG

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"

jobs:
  generate_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate GitHub contribution grid snake
        uses: Platane/snk@v3
        with:
          github_user_name: sairamrockhy
          svg_out_path: dist/github-contribution-grid-snake.svg
          svg_dark_mode_path: dist/github-contribution-grid-snake-dark.svg
          svg_dark_mode_palette: github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git diff --cached --exit-code || git commit -m "Update SVG files"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
