name: Generate Animation

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"

  # Manually run the job at any time
  workflow_dispatch:

  # Run on every push to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate GitHub contribution grid snake
        uses: Platane/snk@v3
        with:
          github_user_name: sairamrockhy
          svg_out_path: dist/github-contribution-grid-snake.svg
          svg_dark_mode_path: dist/github-contribution-grid-snake-dark.svg
          svg_dark_mode_palette: github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --global user.name "sairamrockhy"
          git config --global user.email "SAIRAM1582003@gmail.com"
          git add dist/  # Add all files in the dist/ directory
          git commit -m "Update SVG files"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
